"""added users and user identities tables.

Revision ID: 092e866fe236
Revises: 
Create Date: 2025-04-23 05:32:37.652600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092e866fe236'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_identities_user_id', table_name='user_identities')
    op.create_unique_constraint(op.f('uq_user_identities_user_id'), 'user_identities', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_identities_user_id'), 'user_identities', type_='unique')
    op.create_index('ix_user_identities_user_id', 'user_identities', ['user_id'], unique=False)
    # ### end Alembic commands ###
