"""Added staff invitations table

Revision ID: 0eb7f3b3c687
Revises: 79816346d773
Create Date: 2025-04-28 11:50:16.438452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb7f3b3c687'
down_revision: Union[str, None] = '79816346d773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_invitations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_staff_invitations_seller_id_sellers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_invitations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'seller_id', name=op.f('pk_staff_invitations'))
    )
    op.create_index(op.f('ix_staff_invitations_seller_id'), 'staff_invitations', ['seller_id'], unique=False)
    op.create_index(op.f('ix_staff_invitations_user_id'), 'staff_invitations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_invitations_user_id'), table_name='staff_invitations')
    op.drop_index(op.f('ix_staff_invitations_seller_id'), table_name='staff_invitations')
    op.drop_table('staff_invitations')
    # ### end Alembic commands ###
