"""added invitation code field

Revision ID: 3ff4a55c768f
Revises: c40382f363be
Create Date: 2025-05-20 07:12:27.977808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff4a55c768f'
down_revision: Union[str, None] = 'c40382f363be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invitation_code', sa.String(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_invitation_code'), 'users', ['invitation_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_invitation_code'), 'users', type_='unique')
    op.drop_column('users', 'invitation_code')
    # ### end Alembic commands ###
