"""unique company name field

Revision ID: 61a38c297f7b
Revises: fed0dfd32291
Create Date: 2025-04-27 11:09:16.191480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a38c297f7b'
down_revision: Union[str, None] = 'fed0dfd32291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_sellers_company_name'), 'sellers', ['company_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_sellers_company_name'), 'sellers', type_='unique')
    # ### end Alembic commands ###
