"""status field to staff invitation

Revision ID: 68d655c6e920
Revises: 0eb7f3b3c687
Create Date: 2025-04-29 05:11:50.442512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d655c6e920'
down_revision: Union[str, None] = '0eb7f3b3c687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_user_only_one_accepted', 'staff_invitations', ['user_id'], unique=True, postgresql_where=sa.text("status = 'ACCEPTED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_only_one_accepted', table_name='staff_invitations', postgresql_where=sa.text("status = 'ACCEPTED'"))
    # ### end Alembic commands ###
