"""uq on seller staff table.

Revision ID: 79816346d773
Revises: eb6c928ef526
Create Date: 2025-04-28 11:20:53.989528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79816346d773'
down_revision: Union[str, None] = 'eb6c928ef526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_seller', 'seller_staff', ['user_id', 'seller_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_seller', 'seller_staff', type_='unique')
    # ### end Alembic commands ###
