"""added

Revision ID: a6dd9121b01e
Revises: cd4873ab0690
Create Date: 2025-04-22 10:18:15.632150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6dd9121b01e'
down_revision: Union[str, None] = 'cd4873ab0690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_identities', sa.Column('username', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_column('user_identities', 'username')
    # ### end Alembic commands ###
