"""uq constraint on provider_staff

Revision ID: c40382f363be
Revises: cc0bce69f763
Create Date: 2025-05-20 06:31:36.978349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40382f363be'
down_revision: Union[str, None] = 'cc0bce69f763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_id_provider_id', 'provider_staff', ['user_id', 'provider_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_id_provider_id', 'provider_staff', type_='unique')
    # ### end Alembic commands ###
