"""seller_staff_roles table

Revision ID: e2eb1d08bbc1
Revises: 68d655c6e920
Create Date: 2025-04-30 09:01:12.979037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2eb1d08bbc1'
down_revision: Union[str, None] = '68d655c6e920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_staff_roles',
    sa.Column('seller_staff_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_seller_staff_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_staff_id'], ['seller_staff.id'], name=op.f('fk_seller_staff_roles_seller_staff_id_seller_staff'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('seller_staff_id', 'role_id', name=op.f('pk_seller_staff_roles'))
    )
    op.create_index(op.f('ix_seller_staff_roles_role_id'), 'seller_staff_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_seller_staff_roles_seller_staff_id'), 'seller_staff_roles', ['seller_staff_id'], unique=False)
    op.drop_constraint('fk_seller_staff_role_id_roles', 'seller_staff', type_='foreignkey')
    op.drop_column('seller_staff', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_staff', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_seller_staff_role_id_roles', 'seller_staff', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_seller_staff_roles_seller_staff_id'), table_name='seller_staff_roles')
    op.drop_index(op.f('ix_seller_staff_roles_role_id'), table_name='seller_staff_roles')
    op.drop_table('seller_staff_roles')
    # ### end Alembic commands ###
